/**
 * This is an autogenerated file created by the Stencil build process.
 * It contains typing information for all components that exist in this project
 * and imports for stencil collections that might be configured in your stencil.config.js file
 */

import '@stencil/router';

import { MyApp as MyApp } from './components/my-app/my-app';

interface HTMLMyAppElement extends MyApp, HTMLElement {
}
declare var HTMLMyAppElement: {
  prototype: HTMLMyAppElement;
  new (): HTMLMyAppElement;
};
declare global {
  interface HTMLElementTagNameMap {
      "my-app": HTMLMyAppElement;
  }
  interface ElementTagNameMap {
      "my-app": HTMLMyAppElement;
  }
  namespace JSX {
      interface IntrinsicElements {
          "my-app": JSXElements.MyAppAttributes;
      }
  }
  namespace JSXElements {
      export interface MyAppAttributes extends HTMLAttributes {
        
      }
  }
}

import { Datepicker as MyDatepicker } from './components/my-datepicker/my-datepicker';

interface HTMLMyDatepickerElement extends MyDatepicker, HTMLElement {
}
declare var HTMLMyDatepickerElement: {
  prototype: HTMLMyDatepickerElement;
  new (): HTMLMyDatepickerElement;
};
declare global {
  interface HTMLElementTagNameMap {
      "my-datepicker": HTMLMyDatepickerElement;
  }
  interface ElementTagNameMap {
      "my-datepicker": HTMLMyDatepickerElement;
  }
  namespace JSX {
      interface IntrinsicElements {
          "my-datepicker": JSXElements.MyDatepickerAttributes;
      }
  }
  namespace JSXElements {
      export interface MyDatepickerAttributes extends HTMLAttributes {
        
          options?: any
      }
  }
}

